services:
  watchdog:
    image: xcrypt0r/watchdog:latest
    env_file:
        - .env
    volumes:
        - ${LOCAL_ARCHIVE_DIR}:${DOCKER_ARCHIVE_DIR}
    environment:
        - LOCAL_ARCHIVE_DIR=${DOCKER_ARCHIVE_DIR}
        - TZ=Asia/Seoul
    restart: always